server:
  port: 8080

spring:
  application:
    name: cd2026-curd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cd2026?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      initialization-fail-timeout: -1
  rabbitmq:
    host: 118.24.73.32
    port: 15333
    virtual-host: my_vhost
    username: admin
    password: 123456
    listener:
      simple:
        acknowledge-mode: auto
        default-requeue-rejected: false
  mail:
    host: smtp.qq.com
    port: 587
    username: 1332685225@qq.com
    password: lzjaajdtgczljahh
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    from: 1332685225@qq.com
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cd.entity
  configuration:
    map-underscore-to-camel-case: true


app:
  probe:
    auto-probe-enabled: true
    auto-probe-cron: "0 */5 * * * ?"
  upload-dir: uploads
  database:
    initialize-on-startup: true
  jwt:
    secret: dGhyZWF0LWF3YXJlbmVzcy1wbGF0Zm9ybS1qd3Qtc2VjcmV0LWtleS0yMDI2LTA2LTAy
    expiration-seconds: 43200
